### ISSUE TITLE
I was someone else

### ISSUE THREAD

**Issue by khonkhortisan** [jac241/anki_killstreaks#14]
I made an account as Khonkhortisan, my verification email didn't arrive, got a score of 48, got a bunch of json on my card, now I'm logged in as Dr. Frizzly, got 8 points, while the real Dr. Frizzly didn't register any points
![imagen](https://user-images.githubusercontent.com/1996449/87471119-ad542b80-c5d2-11ea-8627-845f4b334ef8.png)
![imagen](https://user-images.githubusercontent.com/1996449/87471843-daeda480-c5d3-11ea-89fc-38631d97483d.png)
![imagen](https://user-images.githubusercontent.com/1996449/87471151-b80ec080-c5d2-11ea-8cd7-fce17fb44bb6.png)

**Comment by khonkhortisan** [comment]
Notified the account owner of this thread, and logged out.

**Comment by jac241** [comment]
Thanks for reaching out. I will take a look into it. When you signed up on the website were you logged in as yourself or as someone else? I got rid of the email verification and it should auto log you in once you've signed up.

**Comment by jac241** [comment]
Did you try logging back in as yourself? If so, did it work and did you still get the random json or something else.

**Comment by khonkhortisan** [comment]
I was in a review session with it telling me to log in, I only created one account and intentionally logged into that one account. I did go through a few cards in I think each state of no account, account but not logged in, logged in, that weird json on multiple cards, being logged in as someone else (to try to get the account's username from the leaderboard), being logged in as me again to make sure the score increments again.
Oh it just jumped from 48 to ~~81~~ 85 in one go. Anki said 81, I looked at the leaderboard and it said 85, I looked back at Anki and it said 85 as well.
![imagen](https://user-images.githubusercontent.com/1996449/87473976-2ce3f980-c5d7-11ea-980e-a94107f72b82.png)

**Comment by khonkhortisan** [comment]
More info: earlier, <div id="chase mode"> was directly filled with that json without having <table id="rivalry"> in it

**Comment by jac241** [comment]
In terms of being signed on as another user I'm at a loss for why that would happen. I deferred writing any of the token authentication used on the anki client to the library devise_token_auth .

**Comment by jac241** [comment]
Refer to issue #16 for further work on this.
