### ISSUE TITLE
How do I remove the message in the bottom lefthand corner during reviews?

### ISSUE THREAD

**Issue by adotiwal** [jac241/anki_killstreaks#15]
After downloading this addon, I got a message in the bottom lefthand corner while reviewing that says:

"Sign up and log in to AnkiAchievements.com via "Killstreaks" --> "Profile Settings..." 
to activate chase mode, or hide it in the Killstreaks menu. 
(What's this?)"

How can I remove that? It's pretty distracting. 
![Screen Shot 2020-07-14 at 7 53 52 PM](https://user-images.githubusercontent.com/68308369/87490696-f1afed80-c60b-11ea-87a9-7dc54030470c.png)

**Comment by jac241** [comment]
Uncheck this box in the killstreaks menu

![image](https://user-images.githubusercontent.com/3792672/87490777-7bfc4f80-c614-11ea-8e62-be9740adefb4.png)

**Comment by jac241** [comment]
Let me know if that works for you. If it doesn't then I've got an issue I need to deal with :-).

**Comment by adotiwal** [comment]
It did work - thanks so much!

Any chance you're working on adding sound effects to this add-on? I saw
another poster requesting that and after using it I feel like it would be
extremely cool. But so far it's already really cool, really helping to
motivate me to study!


*Ary K. Dotiwala*
