### ISSUE TITLE
Double vision

### ISSUE THREAD

**Issue by sslater11** [jac241/anki_killstreaks#18]
I see the medals twice when I open a deck.
This is due to the new killstreak update v 2.0.1
Anki Version 2.1.22 (0ecc189a)
Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
OS: Ubuntu 20.04

Screenshot here
[https://i.postimg.cc/xdwH2fhK/anki-killstreak-double.png](https://i.postimg.cc/xdwH2fhK/anki-killstreak-double.png)

**Comment by jac241** [comment]
Nice issue title. If you go into Tools-->Add-ons in Anki do you see Anki Killstreaks listed twice?

**Comment by sslater11** [comment]
Sorry for the abrupt post lol I was busy when I posted this.

But yes... yep... 100% my fault lmao.
I made a backup before I updated it lmao, so there were 2 addons in the folder! I was gonna edit some of your code and have a look at it for an idea I had for gamifying Anki.
At some point I want to make Anki look like an actual game, and your chase mode score and rank seem to show over images which is similar to what I was wanting.

**Comment by jac241** [comment]
Awesome that sounds like a cool idea. I would love to help but my 3rd year of med school is going to be much busier than last year was.

**Comment by sslater11** [comment]
I mean you're studying medicine and you can program, that's pretty dam impressive!

I'm working on a video for a friend at the moment( only a beginner at 3D animation ) so that'll take me about a month then I can work on my idea.

My idea is to have a skater guy in the background of our cards with a constant scrolling background(hopefully not distracting). When you answer a card right he does a kickflip, and bails when you fail. After you fail a card, or every x cards you get a level screen that says "Answer x cards correctly". I was playing klax and found it addictive and I think it's because every time I failed it said "Get 15 diagonals" and I think "oh, easy", and 2 hours later still there lol. So I wanna try a simple "Just 5 cards..." idea.

Also, on a personal note. I don't know anyone med wise, so I'd like to ask if you know of any way for me to learn a lot of really useful medical stuff? I couldn't handle being a doctor, but I have wanted to have a good general medical knowledge(just for first aid situations). I want to know more than a first aider, maybe close to an EMT if even possible lol. I have been to 3 first aid courses and I have learnt absolutely nothing(poor teaching, plus no SRS). Is there a place with an 80/20 rule to learn from? Or maybe you've seen something and "though everyone should know of this".
