### ISSUE TITLE
Killstreaks modification

### ISSUE THREAD

**Issue by mnhende2** [jac241/anki_killstreaks#2]
@jac241:  Thanks for making this addon.  My family all use Anki and love it.  I wasn't sure where to post a question, and didn't want to put it on the addons page, so I hope posting it here is preferred.  

Anyhow, is there anyway I can modify the addon to have "hard" count as part of the streak?  Right now only good and easy count towards the killstreak, but we'd like to have "hard" count also, as we regularly press "hard" when doing reviews.

Thanks in advance for any response.

**Comment by jac241** [comment]
Hey this is the right place to reach out. I've been thinking about changing it to include hard. I'll try to get it done in the next couple days then I'll make a post here and update it on ankiweb.

**Comment by jac241** [comment]
The newest version on Ankiweb implements this!

**Comment by mnhende2** [comment]
Thanks! I'll download the new version now.

**Comment by starwarsstan** [comment]
Is there a way to turn this off or have Hard as an option to include?
