### ISSUE TITLE
Glitch allowing for awards without flipping cards

### ISSUE THREAD

**Issue by itsbeenaminute1** [jac241/anki_killstreaks#20]
Hello, I discovered a glitch that allows for an award without flipping cards. If you are on a card without flipping, you can hit the "3" or "Good" button repeatedly and indefinitely resulting in awards and streaks. Sometimes can hit 3/good accidentally skewing results.  Just wanted to point that out in case it can be fixed, thanks!

**Comment by mnhende2** [comment]
The issue exists with all keys 1-4.  Even before you hit "show answer", if you press any number (1-4) Anki Killstreaks reads it as an answers.  

So, if you just spam 2, 3, or 4, it keeps increasing the killstreak.  Someone could just spam one of these numbers a thousand times in a row in a few seconds and have an insane killstreak, all the while never having actually answered a card.  That wouldn't do anything of actual personal achievement, but could be a way for someone to hack their way to the top of the leaderboard.

Similarly, if you accidentally press a "1" (before showing the answer), it will break your streak even though you haven't actually answered the card.  And there isn't anyway to undo that.

Also, it seems that the add-on doesn't process when you undo an answer "Ctrl + Z"

So, if you answer a card, show the answer, and accidentally mark it wrong, and then quickly undo it and press "good" (for example), Anki Killstreaks does not account for this, and will still consider the streak broken, and will then consider pressing "good" as the start of a new streak.  

This also allows for someone to hack the leaderboard, even if the former problem gets fixed.  Even if someone can no longer press 3 endlessly to create a false streak, a determined person could press 3 > Ctrl + Z > 3 > Ctrl + Z > 3 > Ctrl + Z > 3 > Ctrl + Z > 3 , over and over and rack up a false killstreak.

I hate to write all of that, but I am a dad with four boys and they are competitive and have learned these ways. 😞 

Despite this report, my boys and I love the addon.

**Comment by mnhende2** [comment]
@jac241 I just realized you had already mentioned these as bugs:
https://github.com/jac241/anki_killstreaks/issues/10
https://github.com/jac241/anki_killstreaks/issues/9

**Comment by itsbeenaminute1** [comment]
Yes I made this report because there have been a few people who have wasted their add-on download with this killstreak hack. I do like this add-on but wish there was someway to prevent the leaderboard hackers cus I just want to be in first place lol

**Comment by jac241** [comment]
@mnhende2 Thanks for the kind words about the add-on. I have a fix in mind for the spamming the 1,2,3,4 issue but am very busy with medical school and am not sure when I can implement the fix. Supporting undo appropriately is a little bit more involved and may not happen long term. Quicker fix is to just set a minimum time between answers to continue the streak, which is already implemented. I agree it's frustrating with the one person on the leaderboard scoring so high but it doesn't look like he is just spamming the button every day. I think their cards are very easy or he very rarely marks "Again" in Anki.

**Comment by mnhende2** [comment]
@jac241:  Understood!  My to-do list is much longer than life realities allow me to tackle.  Anyhow, wishing the best in med school!  And wishing you relatively smooth and quick solutions when you do tackle these issues.
