### ISSUE TITLE
Appearing when chase mode not turned on

### ISSUE THREAD

**Issue by Prof-Max** [jac241/anki_killstreaks#22]
Chase mode appears when it isn't turned on - very distracting

**Comment by jac241** [comment]
I'm sorry this is happening for you. What anki version and operating system are you using? You can revert to the old version by deleting anki killstreaks from the add-on menu in anki, then installing the .ankiaddon file here - https://github.com/jac241/anki_killstreaks/releases/tag/v1.0.1

**Comment by Prof-Max** [comment]
Thanks for the quick reply! Found out it was because I had chase mode on from another profile, so all sorted now
