### ISSUE TITLE
Did not receive password reset email after 3 attempts

### ISSUE THREAD

**Issue by tipthescalesx3** [jac241/anki_killstreaks#24]
I've been trying to retrieve my password for the email "elisa.marte@live.com" for almost a week. I check my junk mail everyday, I check my inbox and it's still not there :(

Also if i don't answer the cards right away, is the score supposed to decrease?

**Comment by jac241** [comment]
It looks like live.com is blocking emails from my site/sendgrid for some reason. Check your email for a message from my personal email address.
