### ISSUE TITLE
It seems  I am earning less points than usual despite the same amount of cards per day?

### ISSUE THREAD

**Issue by itsbeenaminute1** [jac241/anki_killstreaks#26]
I am looking at competitors who have a ranking above mine, especially in the weekly category and it seems I have more of the same medals (or the same amount of medals as someone a few ranks higher) and therefore should be ranked higher than I am, with more points. I am not sure what's going on... username: want2bepathologist. Has there been a change in point system?

**Comment by jac241** [comment]
Medal scoring and calculation hasn't changed since I launched the site. I think they may have more of the Killionaire medals than you, which is pretty valuable at 50 points. If you hover your mouse over the medals on the website you can see how many points they're worth.

**Comment by itsbeenaminute1** [comment]
OK thanks!
