### ISSUE TITLE
Sync issue?

### ISSUE THREAD

**Issue by itsbeenaminute1** [jac241/anki_killstreaks#28]
![possible-sync-problem](https://user-images.githubusercontent.com/68516296/98723776-d312f680-2360-11eb-9263-66995db0a3cb.png)

I noticed that my medals on the leaderboard don't match the medals I have earned today. I am not sure if there is a synchronizing problem?

**Comment by jac241** [comment]
The today in Anki is based on the setting "day starts at" setting within anki itself. The leaderboard is based on the past 24 hours. These can get out of sync if anki has been open for awhile. You can also try restarting anki. The add-on will do a full sync then.

**Comment by jac241** [comment]
Are you still seeing this as an issue? I made some modifications on the website that I think might address this problem.

**Comment by itsbeenaminute1** [comment]
I haven't checked recently now that I'm on winter break. I'm sure it's fine.
