### ISSUE TITLE
Option to Remove Hard from Continuing Streaks

### ISSUE THREAD

**Issue by starwarsstan** [jac241/anki_killstreaks#3]
I noticed including "hard" presses in streaks was part of the most recent update. Is there a way to turn this off or have "Hard" as an option to include?

**Comment by starwarsstan** [comment]
Any update on this? Or is there anything I can adjust in the code to change it back to the previous version?

**Comment by jac241** [comment]
I am planning a big update in the next week or so and I will make this configurable in that update.

**Comment by jac241** [comment]
If you are using the V2 scheduler, then changing the integer from 1 to 2 on this line in your addon directory may work. No guarantees though.

https://github.com/jac241/anki_killstreaks/blob/b52796b328f1c246b0ba0a8258f085ce67589678/anki_killstreaks/main.py#L149

**Comment by starwarsstan** [comment]
Exciting! I think that temporary fix worked. But I'm excited for the update. Thanks for this great addon and your other contributions to the community!
