### ISSUE TITLE
Chase Mode stopped working

### ISSUE THREAD

**Issue by princessfinger** [jac241/anki_killstreaks#31]
I loved this add-on but "chase mode" suddenly stopped working and it now always says "start reviewing to get ranked" and does not change. I tried turning off all of my add-ons except this one. I tried downgrading to an older version of Anki. I even tried making a new account on ankiachievements.com. Nothing seems to work. Please help!

**Comment by Allandriel277** [comment]
having the same issue, please help!

**Comment by jac241** [comment]
Thanks for letting me know working on this.

**Comment by princessfinger** [comment]
it's working now! thank you so much!!!

**Comment by jac241** [comment]
You're welcome. Thanks again for letting me know it was down.
