### ISSUE TITLE
this add-on not wrorking

### ISSUE THREAD

**Issue by DR-3araby** [jac241/anki_killstreaks#33]
![image](https://user-images.githubusercontent.com/63804491/107699598-f8483580-6cbe-11eb-9e6a-d5d3c75f9f16.png)
![image](https://user-images.githubusercontent.com/63804491/107699621-0007da00-6cbf-11eb-8ad2-6a7e63587eae.png)
we can contact together on my email if you want
a7md.el3araby@gmail.com

**Comment by jac241** [comment]
Hey sorry it is not working. It looks like you are using Anki 2.1.40 and I haven't tried the add-on with that version yet. I only know that it works for sure up to 2.1.35.

**Comment by DR-3araby** [comment]
> Hey sorry it is not working. It looks like you are using Anki 2.1.40 and I haven't tried the add-on with that version yet. I only know that it works for sure up to 2.1.35.
**sorry again 
but still not working after downgrading to 2.1.35**
![image](https://user-images.githubusercontent.com/63804491/107702275-ae614e80-6cc2-11eb-8da4-5807f6abe4f0.png)
![image](https://user-images.githubusercontent.com/63804491/107702299-b91be380-6cc2-11eb-8e5c-4410216d6ce4.png)
**it is my best add-on but I'm incredibly sad that it was not working for a month ago.**

**Comment by jac241** [comment]
Bear with me, and we can try to do something to unlock the anki_killstreaks database and have the add-on work again before I can deploy a fix to go around this issue...

Download and install DB Browser for SQLite, which will let you inspect the contents of the database file I use to save your medals.
![image](https://user-images.githubusercontent.com/3792672/107703596-d84a4f00-6c89-11eb-8bc2-d8baf707033d.png)

Open Anki --> Tools --> Add-ons and find Anki Killstreaks and press view files.
![image](https://user-images.githubusercontent.com/3792672/107703629-e4361100-6c89-11eb-895f-b7ee6399b1ef.png)

Go up two directories until you see your Anki profile's directory (Mine is the default User 1)
![image](https://user-images.githubusercontent.com/3792672/107703675-fb74fe80-6c89-11eb-979f-df33d88019e4.png)

Open that directory and find the anki_killstreaks.db file.
![image](https://user-images.githubusercontent.com/3792672/107703699-0596fd00-6c8a-11eb-9527-18259c291d85.png)

Right click, and open the file with DB Browser for SQLite. Or you can open DB Browser for SQLite and drag the file over the window and it will open.
![image](https://user-images.githubusercontent.com/3792672/107703758-21020800-6c8a-11eb-8c19-e14ac1ff45cb.png)

Click on the table drop down, and select the yoyo_lock table.
![image](https://user-images.githubusercontent.com/3792672/107703833-3d9e4000-6c8a-11eb-80b9-86193df88738.png)

Highlight and delete the record there.
![image](https://user-images.githubusercontent.com/3792672/107703899-5870b480-6c8a-11eb-8664-f3534040bb4d.png)

Write your changes to the database file
![image](https://user-images.githubusercontent.com/3792672/107703961-7b02cd80-6c8a-11eb-8799-fa9fabd27d4a.png)

Then try opening Anki again.

**Comment by DR-3araby** [comment]
It got worked again 😍😍😍😍
Thank you very much

**Comment by jac241** [comment]
No problem happy to help!
