### ISSUE TITLE
Can't install the add-on in anki 2.1.22

### ISSUE THREAD

**Issue by kushapatel07** [jac241/anki_killstreaks#8]
Hey,

I have having problmes installing the add-on in anki 2.1.23.

I have added the list of add-ons I have and also a screenshot  of the error.

Please help!!

Regards,
Kush A. Patel

<img width="324" alt="add-ons" src="https://user-images.githubusercontent.com/62458757/77220531-da488280-6b8c-11ea-9895-bc9aa342d393.PNG">
<img width="434" alt="error" src="https://user-images.githubusercontent.com/62458757/77220532-dc124600-6b8c-11ea-977a-9cc28eef3ee9.PNG">

**Comment by jac241** [comment]
What's your profile named? It looks like right now the add-on isn't working with profiles that have special characters in the name (like / * $, etc.) I'll look at how Anki handles this and hopefully update sooner or later (I'm pretty busy now). As a temporary fix, try renaming your profile.

**Comment by kushapatel07** [comment]
Hey Jac, 

You are right, my profile was named "##Main", I just changed it to "Main" and it WORKED!!
Thank you so much. I can just use it without the symbols, no problem. Fix it whenever you get time no hurry. Again, thanks for your speedy reply.

Regards, 
Kush A. Patel
